# Generated by Django 5.2.1 on 2025-05-31 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_post_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="dislike",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_dislike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
